CREATE TABLE users (
    id VARCHAR(255) PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE accounts (
    id VARCHAR(255) PRIMARY KEY,
    number VARCHAR(15) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    balance DECIMAL NOT NULL DEFAULT 0,
    user_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);
ALTER TABLE accounts ADD CONSTRAINT fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES users(id);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "from" VARCHAR(255) NOT NULL,
    "to" VARCHAR(255) NOT NULL,
    amount DECIMAL NOT NULL,
    transaction_date TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL
);
ALTER TABLE transactions ADD CONSTRAINT fk_transactions_from FOREIGN KEY ("from") REFERENCES accounts(id);
ALTER TABLE transactions ADD CONSTRAINT fk_transactions_to FOREIGN KEY ("to") REFERENCES accounts(id);